[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "AutoPPT"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.2,<3.14"
ipykernel = ">=6.29.5,<6.30"
jupyter = ">=1.1.1,<1.2"
ruff = ">=0.9.7,<0.10"
python-pptx = ">=1.0.2,<1.1"
